name: Build VehicleModulesSystem

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    # Шаг NuGet убираем или оставляем пустым, если нет других зависимостей
    
    - name: Build Plugin
      run: msbuild VehicleModulesSystem.csproj /p:Configuration=Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: VehicleModulesSystem-v7.0
        path: bin/Release/VehicleModulesSystem.dll
